package com.us.person;

import com.us.person.Person;
rule "boy"
    salience 1
    when
        $p : Person(age > 0);
    then
        $p.setDesc("少年");
        retract($p);
end

rule "youth"
    salience 2
    when
        $p : Person(age > 12);
    then
        $p.setDesc("青年");
        retract($p);
end

rule "midlife"
    salience 3
    when
        $p : Person(age > 24);
    then
        $p.setDesc("中年");
        retract($p);
end

rule "old"
  date-effective "12-Sep-2016"
 date-expires "12-Sep-2016"
  salience 5
    when
        $p : Person(age > 60 && age <69)

    then
        $p.setDesc("老年");
        retract($p);
end

rule "bai"
  salience 4
    when
        $p : Person(name contains "白");
    then
        $p.setDesc("我是白展堂");
        retract($p);
end

rule "lao"
  salience 6
    when
        $p : Person(desc contains "老");
    then
        $p.setDesc("我是老年白展堂");
        retract($p);
end